/**
 * BindX V9 — Default Analytics Charts
 * Auto-generates a set of charts based on available columns in the dataset.
 * Titles are auto-generated by ChartCard — no need to set them here.
 */
export function generateDefaultCharts(availableColumns) {
  const has = (key) => availableColumns.some(c => c.key === key)
  const numericCount = availableColumns.filter(c => c.type === 'number').length
  const charts = []

  // 1. Scatter — Docking vs Composite
  if (has('docking_score') && has('composite_score')) {
    charts.push({ type: 'scatter', xKey: 'docking_score', yKey: 'composite_score' })
  }

  // 2. Histogram — Docking Score Distribution
  if (has('docking_score')) {
    charts.push({ type: 'histogram', key: 'docking_score', bins: 20 })
  }

  // 3. Histogram — QED Distribution
  if (has('QED')) {
    charts.push({ type: 'histogram', key: 'QED', bins: 20 })
  }

  // 4. Bar — Safety Classification
  if (has('safety_color_code')) {
    charts.push({ type: 'bar', key: 'safety_color_code' })
  }

  // 5. Pie — Lipinski Pass Rate
  if (has('lipinski_pass')) {
    charts.push({ type: 'pie', key: 'lipinski_pass' })
  }

  // 6. Box — Docking by Cluster
  if (has('docking_score') && has('cluster_id')) {
    charts.push({ type: 'box', metricKey: 'docking_score', groupKey: 'cluster_id' })
  }

  // 7. Correlation Matrix — if at least 3 numeric columns
  if (numericCount >= 3) {
    charts.push({ type: 'correlation' })
  }

  // 8. Top 15 by Composite Score
  if (has('composite_score')) {
    charts.push({ type: 'topn', key: 'composite_score', n: 15 })
  }

  return charts
}
